### ISSUE TITLE
Improve handling of browser reinstalls

### ISSUE THREAD

**Issue by mnmkng** [apify/apify-actor-docker#40]
```
2021-03-05T10:01:18.796Z ERROR PlaywrightCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.leboncoin.fr/messages","retryCount":1,"id":"bFn6QIYXJ7pKp7O"}
2021-03-05T10:01:18.797Z   browserType.launchPersistentContext: Failed to launch firefox because executable doesn't exist at /home/myuser/.cache/ms-playwright/firefox-1234/firefox/firefox
2021-03-05T10:01:18.797Z   Try re-installing playwright with "npm install playwright"Error
2021-03-05T10:01:18.798Z       at Object.captureStackTrace (/home/myuser/node_modules/playwright/lib/utils/stackTrace.js:48:19)
2021-03-05T10:01:18.799Z       at Connection.sendMessageToServer (/home/myuser/node_modules/playwright/lib/client/connection.js 48)
2021-03-05T10:01:18.799Z       at Proxy.<anonymous> (/home/myuser/node_modules/playwright/lib/client/channelOwner.js:64:61)
2021-03-05T10:01:18.800Z       at /home/myuser/node_modules/playwright/lib/client/browserType.js:85:42
2021-03-05T10:01:18.800Z       at async BrowserType._wrapApiCall (/home/myuser/node_modules/playwright/lib/client/channelOwner.js:77:28)
```

This happens whenever the installed version of Playwright does not match either the users `package.json` or `package-lock.json`. I've seen this quite a few times in the last few days so I'm sure it's bothering a lot of users.

We need to figure out a more user friendly way of doing this.

**Comment by B4nan** [comment]
Closing in favor of #87
