### ISSUE TITLE
error in loading shared libraries

### ISSUE THREAD

**Issue by cmabastar** [apify/apify-actor-docker#46]
Hello, 

I'm getting some issues with running docker.

```
INFO  AutoscaledPool state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
INFO  Launching Puppeteer {"headless":true,"stealth":true,"args":["--no-sandbox","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"],"timeout":15000,"defaultViewport":{"width":1366,"height":768},"proxyUrl":"http://auto:<redacted>@proxy.apify.com:8000/"}
ERROR PuppeteerPool: Browser launch failed {"id":0}
  Error: Failed to launch the browser process!
  /home/myuser/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
  
  
  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
  
      at onClose (/home/myuser/node_modules/puppeteer/lib/Launcher.js:750:14)
      at Interface.<anonymous> (/home/myuser/node_modules/puppeteer/lib/Launcher.js:739:50)
      at Interface.emit (events.js:327:22)
      at Interface.close (readline.js:424:8)
      at Socket.onend (readline.js:202:10)
      at Socket.emit (events.js:327:22)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
ERROR BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/search?q=laptop&oq=lawn+leveling+rake&aqs=chrome..69i57.5774j0j7&sourceid=chrome&ie=UTF-8","retryCount":1}
  Error: Failed to launch the browser process!
  /home/myuser/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

```

My docker config is like this:

```
FROM apify/actor-node-puppeteer-chrome    
      
  COPY package.json package-lock.json ./    
      
  # Install default dependencies, print versions of everything    
  RUN npm --quiet set progress=false \    
   && npm install --only=prod --no-optional \    
   && echo "Installed NPM packages:" \    
   && npm list || true \    
   && echo "Node.js version:" \    
   && node --version \    
   && echo "NPM version:" \    
   && npm --version    
       
  COPY . ./    
  ENV APIFY_LOCAL_STORAGE_DIR /tmp/    
  ENV APIFY_TOKEN token    
  ENV APIFY_PROXY_PASSWORD pass    
      
  EXPOSE 8080    
  CMD [ "node", "main.js" ]    
```

**Comment by cmabastar** [comment]
Fixed it by adding

```
USER root
RUN apt-get update && apt-get install -y libxtst6
```

**Comment by mnmkng** [comment]
Thanks, added it to the image.
