### ISSUE TITLE
Failing builds

### ISSUE THREAD

**Issue by mnmkng** [apify/apify-actor-docker#63]
Our builds are getting a bit out of date. The big playwright image build was failing for quite some time, but I did not consider it a priority, but now even the Puppeteer image build failed. Let's fix it.

**Comment by szmarczak** [comment]
looks like the os is not posix compliant (playwright)

https://github.com/apify/apify-actor-docker/runs/3525958059?check_suite_focus=true#step:9:27

**Comment by szmarczak** [comment]
puppeteer fails because it tries to configure it with [too] newer versions: https://github.com/apify/apify-actor-docker/runs/3525957951?check_suite_focus=true#step:9:50

**Comment by szmarczak** [comment]
![zzzz](https://user-images.githubusercontent.com/36894700/132300154-8b11f5b3-255c-4ed3-9280-51ae4ed5dde2.png)

hmm

**Comment by szmarczak** [comment]
Actually it's a docker thing: https://github.com/cypress-io/cypress/issues/4925

**Comment by szmarczak** [comment]
```
  [pid=2947][err] [2947:2970:0906/150516.687409:ERROR:gpu_process_host.cc(961)] GPU process exited unexpectedly: exit_code=132
```

Does GitHub Actions run with GPU?

**Comment by szmarczak** [comment]
Looks like #64 fixed the playwright issues

**Comment by szmarczak** [comment]
@mnmkng Can you try building against puppeteer `10.2.0`?

**Comment by mnmkng** [comment]
It's running 🤝 You can always run it yourself like this. Just dont use the `beta` or `latest` tag.

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/23726914/132313715-b05592cd-c755-4053-a981-480eafe88de4.png">

**Comment by szmarczak** [comment]
> Just dont use the beta or latest tag.

👍🏼 Will remember now. For playwright I reused the values from your build.

**Comment by szmarczak** [comment]
I think we can close this now?

**Comment by mnmkng** [comment]
Yeah, thanks for the quick fix. Please bump the playwright and puppeteer versions to latest Chrome in apify dev deps before closing. That's where they're taken from when the build is auto triggered on SDK release.

**Comment by szmarczak** [comment]
https://github.com/apify/apify-js/commit/f9cbf8fa72bb4af7871d1219b39dd15d18b28d60

Will close this once the beta is released.

**Comment by B4nan** [comment]
Looks like the pw-webkit ones are now failing:

https://github.com/apify/apify-actor-docker/runs/3531918312?check_suite_focus=true

**Comment by szmarczak** [comment]
```
  ==================== Browser output: ====================
  <launching> /home/myuser/pw-browsers/MiniBrowser --inspector-pipe --headless --user-data-dir=/tmp/2xs54QHz9bZG2QtYvUNVY about:blank
  <launched> pid=43
  [pid=43][err] /home/myuser/pw-browsers/webkit-1530/minibrowser-gtk/bin/MiniBrowser: error while loading shared libraries: libevdev.so.2: cannot open shared object file: No such file or directory
  [pid=43] <process did exit: exitCode=127, signal=null>
  [pid=43] starting temporary directories cleanup
  =========================== logs ===========================
  <launching> /home/myuser/pw-browsers/MiniBrowser --inspector-pipe --headless --user-data-dir=/tmp/2xs54QHz9bZG2QtYvUNVY about:blank
  <launched> pid=43
  [pid=43][err] /home/myuser/pw-browsers/webkit-1530/minibrowser-gtk/bin/MiniBrowser: error while loading shared libraries: libevdev.so.2: cannot open shared object file: No such file or directory
  [pid=43] <process did exit: exitCode=127, signal=null>
  [pid=43] starting temporary directories cleanup
  ============================================================
```

What's `MiniBrowser`?

**Comment by mnmkng** [comment]
> What's `MiniBrowser`?

No idea 🤷‍♂️ Playwright uses custom builds of browsers so maybe MiniBrowser is some custom build of WebKit.

**Comment by mnmkng** [comment]
How's this looking? I still get a lot of notifications about the failed builds.

**Comment by szmarczak** [comment]
Installed `libevdev2` and it launches successfully. The must have added this as a new dependency.

**Comment by rubydev** [comment]
Hi, I'm not able build docker images like:

```
FROM apify/actor-node-puppeteer-chrome:14
FROM apify/actor-node-puppeteer-chrome:14-10.2.0
FROM apify/actor-node-puppeteer-chrome:14-9.1.0
```

I tried package.json with `"puppeteer": "*"` also `"puppeteer": "10.2.0"` and `"puppeteer": "9.1.0"`. 

Always same error:

```
2021-09-16T17:06:01.220Z Step 14/18 : RUN npm --quiet set progress=false   && npm install --only=prod --no-optional   && echo "Installed NPM packages:"   && (npm list || true)   && echo "Node.js version:"   && node --version   && echo "NPM version:"   && npm --version
2021-09-16T17:06:01.312Z  ---> Running in a205b690ae09
2021-09-16T17:06:04.854Z npm WARN deprecated @types/socket.io-parser@3.0.0: This is a stub types definition. socket.io-parser provides its own type definitions, so you do not need this installed.
2021-09-16T17:06:04.855Z 
2021-09-16T17:06:11.598Z > better-sqlite3-with-prebuilds@7.4.3 install /home/myuser/app/node_modules/better-sqlite3-with-prebuilds
2021-09-16T17:06:11.599Z > prebuild-install || npm run build-release
2021-09-16T17:06:11.836Z prebuild-install 
2021-09-16T17:06:11.836Z WARN install No prebuilt binaries found (target=14.17.6 runtime=node arch=x64 libc= platform=linux)
2021-09-16T17:06:11.837Z 
2021-09-16T17:06:12.072Z > better-sqlite3-with-prebuilds@7.4.3 build-release /home/myuser/app/node_modules/better-sqlite3-with-prebuilds
2021-09-16T17:06:12.073Z > node-gyp rebuild --release
2021-09-16T17:06:12.207Z gyp
2021-09-16T17:06:12.208Z  ERR! find Python 
2021-09-16T17:06:12.209Z gyp 
2021-09-16T17:06:12.210Z ERR! 
2021-09-16T17:06:12.210Z find Python
2021-09-16T17:06:12.211Z  Python is not set from command line or npm configuration
2021-09-16T17:06:12.212Z gyp ERR! 
2021-09-16T17:06:12.213Z find Python checking if "python" can be used
2021-09-16T17:06:12.211Z gyp ERR! find Python
2021-09-16T17:06:12.212Z  Python is not set from environment variable PYTHON
2021-09-16T17:06:12.213Z gyp 
2021-09-16T17:06:12.214Z find Python
2021-09-16T17:06:12.214Z ERR! 
2021-09-16T17:06:12.215Z  - "python" is not in PATH or produced an error
2021-09-16T17:06:12.216Z gyp ERR! 
2021-09-16T17:06:12.216Z find Python checking if "python2" can be used
2021-09-16T17:06:12.215Z 
2021-09-16T17:06:12.216Z gyp
2021-09-16T17:06:12.217Z  ERR! find Python - "python2" is not in PATH or produced an error
2021-09-16T17:06:12.217Z 
2021-09-16T17:06:12.218Z gyp 
2021-09-16T17:06:12.218Z ERR! find Python checking if "python3" can be used
2021-09-16T17:06:12.219Z gyp 
2021-09-16T17:06:12.219Z ERR! find Python
2021-09-16T17:06:12.220Z  - "python3" is not in PATH or produced an error
2021-09-16T17:06:12.220Z 
2021-09-16T17:06:12.220Z gyp ERR! find Python
2021-09-16T17:06:12.221Z gyp ERR! 
2021-09-16T17:06:12.221Z find Python **********************************************************
2021-09-16T17:06:12.222Z gyp ERR!
2021-09-16T17:06:12.221Z  
2021-09-16T17:06:12.222Z  find Python You need to install the latest version of Python.
2021-09-16T17:06:12.222Z 
2021-09-16T17:06:12.223Z gyp
2021-09-16T17:06:12.223Z  ERR!
2021-09-16T17:06:12.224Z  
2021-09-16T17:06:12.224Z find Python Node-gyp should be able to find and use Python. If not,
2021-09-16T17:06:12.225Z 
2021-09-16T17:06:12.225Z gyp 
2021-09-16T17:06:12.226Z ERR!
2021-09-16T17:06:12.227Z find Python you can try one of the following options:
2021-09-16T17:06:12.227Z gyp 
2021-09-16T17:06:12.226Z  
2021-09-16T17:06:12.228Z gyp
2021-09-16T17:06:12.229Z  
2021-09-16T17:06:12.229Z ERR! find Python   (accepted by both node-gyp and npm)
2021-09-16T17:06:12.227Z ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2021-09-16T17:06:12.228Z 
2021-09-16T17:06:12.231Z ERR! find Python - Set the environment variable PYTHON
2021-09-16T17:06:12.231Z gyp ERR!
2021-09-16T17:06:12.230Z gyp 
2021-09-16T17:06:12.232Z  find Python - Set the npm configuration variable python:
2021-09-16T17:06:12.233Z gyp ERR! find Python
2021-09-16T17:06:12.233Z    npm config set python "/path/to/pythonexecutable"
2021-09-16T17:06:12.234Z gyp ERR!
2021-09-16T17:06:12.234Z  
2021-09-16T17:06:12.235Z find Python For more information consult the documentation at:
2021-09-16T17:06:12.236Z ERR!
2021-09-16T17:06:12.235Z 
2021-09-16T17:06:12.236Z gyp 
2021-09-16T17:06:12.237Z  
2021-09-16T17:06:12.237Z find Python
2021-09-16T17:06:12.237Z  https://github.com/nodejs/node-gyp#installation
2021-09-16T17:06:12.238Z gyp
2021-09-16T17:06:12.239Z  
2021-09-16T17:06:12.239Z ERR! find Python
2021-09-16T17:06:12.239Z  **********************************************************
2021-09-16T17:06:12.240Z gyp ERR! find Python 
2021-09-16T17:06:12.240Z 
2021-09-16T17:06:12.241Z gyp ERR!
2021-09-16T17:06:12.242Z  
2021-09-16T17:06:12.244Z 
2021-09-16T17:06:12.241Z  configure error
2021-09-16T17:06:12.244Z gyp ERR! stack Error: Could not find any Python installation to use
2021-09-16T17:06:12.245Z gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
2021-09-16T17:06:12.245Z gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
2021-09-16T17:06:12.246Z 
2021-09-16T17:06:12.246Z gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
2021-09-16T17:06:12.247Z 
2021-09-16T17:06:12.248Z gyp 
2021-09-16T17:06:12.248Z ERR! 
2021-09-16T17:06:12.249Z      at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
2021-09-16T17:06:12.249Z gyp ERR! stack     at exithandler (child_process.js:397:5)
2021-09-16T17:06:12.250Z gyp 
2021-09-16T17:06:12.248Z stack
2021-09-16T17:06:12.250Z ERR! stack     at ChildProcess.errorhandler (child_process.js:409:5)
2021-09-16T17:06:12.251Z gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
2021-09-16T17:06:12.253Z gyp 
2021-09-16T17:06:12.254Z gyp 
2021-09-16T17:06:12.255Z ERR!
2021-09-16T17:06:12.252Z 
2021-09-16T17:06:12.252Z gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2021-09-16T17:06:12.254Z ERR! stack     at onErrorNT (internal/child_process.js:467:16)
2021-09-16T17:06:12.255Z  stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
2021-09-16T17:06:12.255Z 
2021-09-16T17:06:12.257Z gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
2021-09-16T17:06:12.258Z 
2021-09-16T17:06:12.258Z gyp ERR! cwd /home/myuser/app/node_modules/better-sqlite3-with-prebuilds
2021-09-16T17:06:12.256Z gyp ERR! System Linux 4.14.243-185.433.amzn2.x86_64
2021-09-16T17:06:12.257Z 
2021-09-16T17:06:12.259Z 
2021-09-16T17:06:12.259Z gyp ERR! node -v v14.17.6
2021-09-16T17:06:12.260Z 
2021-09-16T17:06:12.261Z 
2021-09-16T17:06:12.261Z gyp ERR! not ok 
2021-09-16T17:06:12.262Z npm ERR! 
2021-09-16T17:06:12.263Z code ELIFECYCLE
2021-09-16T17:06:12.260Z gyp ERR! node-gyp -v v5.1.0
2021-09-16T17:06:12.261Z 
2021-09-16T17:06:12.264Z npm ERR!
2021-09-16T17:06:12.264Z  
2021-09-16T17:06:12.265Z 
2021-09-16T17:06:12.266Z npm ERR! better-sqlite3-with-prebuilds@7.4.3 build-release: `node-gyp rebuild --release`
2021-09-16T17:06:12.266Z npm ERR!
2021-09-16T17:06:12.263Z 
2021-09-16T17:06:12.265Z errno 1
2021-09-16T17:06:12.266Z  Exit status 1
2021-09-16T17:06:12.267Z npm
2021-09-16T17:06:12.267Z  ERR!
2021-09-16T17:06:12.268Z  
2021-09-16T17:06:12.269Z npm
2021-09-16T17:06:12.268Z npm ERR! Failed at the better-sqlite3-with-prebuilds@7.4.3 build-release script.
2021-09-16T17:06:12.269Z  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-09-16T17:06:12.270Z 
2021-09-16T17:06:12.269Z 
2021-09-16T17:06:12.270Z npm WARN Local package.json exists, but node_modules missing, did you mean to install?
2021-09-16T17:06:12.271Z 
2021-09-16T17:06:12.271Z npm 
2021-09-16T17:06:12.272Z ERR! A complete log of this run can be found in:
2021-09-16T17:06:12.272Z      /home/myuser/.npm/_logs/2021-09-16T17_06_12_218Z-debug.log
2021-09-16T17:06:12.273Z 
2021-09-16T17:06:12.272Z npm ERR!
2021-09-16T17:06:12.443Z npm WARN bjs@0.0.1 No repository field.
2021-09-16T17:06:12.445Z 
2021-09-16T17:06:12.444Z 
2021-09-16T17:06:12.445Z 
2021-09-16T17:06:12.454Z npm ERR! code ELIFECYCLE
2021-09-16T17:06:12.455Z npm ERR!
2021-09-16T17:06:12.455Z  errno 1
2021-09-16T17:06:12.456Z 
2021-09-16T17:06:12.457Z npm ERR! better-sqlite3-with-prebuilds@7.4.3 install: `prebuild-install || npm run build-release`
2021-09-16T17:06:12.457Z npm ERR! Exit status 1
2021-09-16T17:06:12.458Z 
2021-09-16T17:06:12.458Z npm ERR! 
2021-09-16T17:06:12.459Z npm ERR!
2021-09-16T17:06:12.460Z  Failed at the better-sqlite3-with-prebuilds@7.4.3 install script.
2021-09-16T17:06:12.461Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-09-16T17:06:12.461Z 
2021-09-16T17:06:12.482Z 
2021-09-16T17:06:12.482Z npm ERR!
2021-09-16T17:06:12.484Z  ERR!     /home/myuser/.npm/_logs/2021-09-16T17_06_12_475Z-debug.log
```

Could you please check it?

**Comment by B4nan** [comment]
Ouch, I was shipping new version of `better-sqlite3-with-prebuilds` and apparently some of the workflows got stuck. Looks like there is no longer a way to use ubuntu 16 with GH actions (which was needed to deal with some other issues):

```
Can't find any online and idle self-hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-16.04'
Waiting for a self-hosted runner to pickup this job...
```

Will try ubuntu 18 and get back to you in a minute.

**Comment by B4nan** [comment]
@rubydev please try again now (you might wanna wipe node_modules and the lockfile too)

**Comment by rubydev** [comment]
@B4nan Thanks! Now it is OK.

**Comment by B4nan** [comment]
Closing, as the issue was originally about docker image builds and those are also working fine now.
