### ISSUE TITLE
Request failed and reached maximum retries. browserType.launchPersistentContext: Executable doesn't exist at /home/myuser/pw-browsers/chromium-1033/chrome-linux/chrome in Docker Env running in AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by SFaraji** [apify/apify-actor-docker#90]
When trying to run my project using Playwright Docker image under AWS Elastic Beanstalk, I get this issue `Request failed and reached maximum retries. browserType.launchPersistentContext: Executable doesn't exist at /home/myuser/pw-browsers/chromium-1033/chrome-linux/chrome`.

Here is my Dockerfile:

```
FROM apify/actor-node-playwright-chrome:16

USER root

ENV PORT 3000

# Copy just package.json and package-lock.json
# to speed up the build using Docker layer cache.
COPY package*.json ./

# Install NPM packages, skip optional and development dependencies to
# keep the image small. Avoid logging too much and print the dependency
# tree for debugging
RUN npm --quiet set progress=false \
    && npm install --omit=dev --omit=optional \
    && echo "Installed NPM packages:" \
    && (npm list --omit=dev --all || true) \
    && echo "Node.js version:" \
    && node --version \
    && echo "NPM version:" \
    && npm --version

# Next, copy the remaining files and directories with the source code.
# Since we do this after NPM install, quick build will be really fast
# for most source file changes.
COPY . ./

# Run the image.
EXPOSE 3000
CMD [ "npm", "start" ]
```

Here is the full snapshot of the log:

```
[31mERROR[39m[33m PlaywrightCrawler:[39m Request failed and reached maximum retries. browserType.launchPersistentContext: Executable doesn't exist at /home/myuser/pw-browsers/chromium-1033/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at async PlaywrightPlugin._launch (/home/myuser/node_modules/@crawlee/browser-pool/playwright/playwright-plugin.js:99:40)
    at async BrowserPool._launchBrowser (/home/myuser/node_modules/@crawlee/browser-pool/browser-pool.js:465:29)
    at async /home/myuser/node_modules/@crawlee/browser-pool/browser-pool.js:274:37[90m {"id":"r41pL1yCrgNgU80","url":"https://www.google.com.au/search?tbm=shop&hl=en-AU&psb=1&ved=2ahUKEwjP49q7gdb7AhUyn0sFHcYhAAQQu-kFegQIABAL&q=Coles+Extra Virgin Avocado Oil 250mL&oq=Coles+Extra Virgin Avocado Oil 250mL&gs_lcp=Cgtwcm9kdWN0cy1jYxADUABYAGAAaABwAHgAgAEAiAEAkgEAmAEA&sclient=products-cc&ts=818","method":"GET","uniqueKey":"https://www.google.com.au/search?gs_lcp=Cgtwcm9kdWN0cy1jYxADUABYAGAAaABwAHgAgAEAiAEAkgEAmAEA&hl=en-AU&oq=Coles+Extra Virgin Avocado Oil 250mL&psb=1&q=Coles+Extra Virgin Avocado Oil 250mL&sclient=products-cc&tbm=shop&ts=818&ved=2ahUKEwjP49q7gdb7AhUyn0sFHcYhAAQQu-kFegQIABAL"}[39m
[32mINFO[39m [33m PlaywrightCrawler:[39m All the requests from request list and/or request queue have been processed, the crawler will shut down.
[32mINFO[39m [33m PlaywrightCrawler:[39m Crawl finished. Final request statistics:[90m {"requestsFinished":0,"requestsFailed":1,"retryHistogram":[null,null,null,1],"requestAvgFailedDurationMillis":11,"requestAvgFinishedDurationMillis":null,"requestsFinishedPerMinute":0,"requestsFailedPerMinute":5,"requestTotalDurationMillis":11,"requestsTotal":1,"crawlerRuntimeMillis":10996}[39m
[32mINFO[39m [33m PlaywrightCrawler:[39m Error analysis:[90m {"totalErrors":1,"uniqueErrors":1,"mostCommonErrors":["1x: browserType.launchPersistentContext: Executable doesn't exist at /home/myuser/pw-browsers/chromium-1033/chrome-linux/chrome (/home/myuser/node_modules/@crawlee/browser-pool/playwright/playwright-plugin.js:99:40)"]}[39m
```

**Comment by SFaraji** [comment]
cc: @mnmkng
